GOOGLE_APPLICATION_CREDENTIALS: '/home/user/Desktop/zoomapp-278612-830aff49a81c.json'
GOOGLE_API_KEY: '457699956270-j675i9ct2da4pv54am3rihjs33vir2tv.apps.googleusercontent.com'
GOOGLE_API_SECRET: '4AHgt_Kq2z-MuZdLfZXCj4kJ'